const nodemailer = require('nodemailer');

const sendEmail = async options => {
  // 1) Create a transporter
  var transport = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: "922f802e80338c", //generated by Mailtrap
      pass: "cd1a0fe77b439e" //generated by Mailtrap
    }
  });
  // 2) Define the email options
  var mailOptions = {
    from: '"Example Team" <from@example.com>',
    to:  options.email,
    subject:  options.subject,
    text: options.message
};

  // 3) Actually send the email
  await transport.sendMail(mailOptions, (error, info) => {
    if (error) {
        return console.log(error);
    }
    console.log('Message sent: %s', info.messageId);
});
};

module.exports = sendEmail;
